export interface MockDestination {
  id: string;
  name: string;
  slug: string;
  iso_code: string;
  region: string;
  image_url: string;
  is_active: boolean;
  popularity_rank: number;
  synced_at: string;
  created_at: string;
  updated_at: string;
}

const now = '2026-04-01T00:00:00Z';

export const mockDestinations: MockDestination[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    name: 'Europe',
    slug: 'europe',
    iso_code: 'EU',
    region: 'europe-wide',
    image_url: '/images/destinations/europe.jpg',
    is_active: true,
    popularity_rank: 0,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    name: 'France',
    slug: 'france',
    iso_code: 'FR',
    region: 'europe',
    image_url: '/images/destinations/france.jpg',
    is_active: true,
    popularity_rank: 1,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    name: 'Spain',
    slug: 'spain',
    iso_code: 'ES',
    region: 'europe',
    image_url: '/images/destinations/spain.jpg',
    is_active: true,
    popularity_rank: 2,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    name: 'Italy',
    slug: 'italy',
    iso_code: 'IT',
    region: 'europe',
    image_url: '/images/destinations/italy.jpg',
    is_active: true,
    popularity_rank: 3,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0005-4000-8000-000000000005',
    name: 'Germany',
    slug: 'germany',
    iso_code: 'DE',
    region: 'europe',
    image_url: '/images/destinations/germany.jpg',
    is_active: true,
    popularity_rank: 4,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Portugal',
    slug: 'portugal',
    iso_code: 'PT',
    region: 'europe',
    image_url: '/images/destinations/portugal.jpg',
    is_active: true,
    popularity_rank: 5,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    name: 'Netherlands',
    slug: 'netherlands',
    iso_code: 'NL',
    region: 'europe',
    image_url: '/images/destinations/netherlands.jpg',
    is_active: true,
    popularity_rank: 6,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0008-4000-8000-000000000008',
    name: 'United Kingdom',
    slug: 'united-kingdom',
    iso_code: 'GB',
    region: 'europe',
    image_url: '/images/destinations/united-kingdom.jpg',
    is_active: true,
    popularity_rank: 7,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0009-4000-8000-000000000009',
    name: 'Greece',
    slug: 'greece',
    iso_code: 'GR',
    region: 'europe',
    image_url: '/images/destinations/greece.jpg',
    is_active: true,
    popularity_rank: 8,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0010-4000-8000-000000000010',
    name: 'Turkey',
    slug: 'turkey',
    iso_code: 'TR',
    region: 'europe',
    image_url: '/images/destinations/turkey.jpg',
    is_active: true,
    popularity_rank: 9,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0011-4000-8000-000000000011',
    name: 'Poland',
    slug: 'poland',
    iso_code: 'PL',
    region: 'europe',
    image_url: '/images/destinations/poland.jpg',
    is_active: true,
    popularity_rank: 10,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0012-4000-8000-000000000012',
    name: 'Czech Republic',
    slug: 'czech-republic',
    iso_code: 'CZ',
    region: 'europe',
    image_url: '/images/destinations/czech-republic.jpg',
    is_active: true,
    popularity_rank: 11,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'a1b2c3d4-0013-4000-8000-000000000013',
    name: 'Austria',
    slug: 'austria',
    iso_code: 'AT',
    region: 'europe',
    image_url: '/images/destinations/austria.jpg',
    is_active: true,
    popularity_rank: 12,
    synced_at: now,
    created_at: now,
    updated_at: now,
  },
];
